"""
Original seed dataset extracted from the Zepto Apriori notebook.
This is the starting point of the transaction log the very first time
the app runs. After that, every order placed inside the app is appended
to data/transactions.csv, which becomes the new source of truth.
"""

SEED_TRANSACTIONS = [
    ['Bread', 'Milk', 'Jam', 'Coffee', 'Curd'],
    ['Bread', 'Apples', 'Coffee'],
    ['Curd', 'Milk', 'Apples', 'Banana'],
    ['Butter', 'Apples', 'Milk'],
    ['Butter', 'Apples', 'Curd', 'Bread'],
    ['Coffee', 'Jam', 'Milk', 'Curd'],
    ['Curd', 'Cheese', 'Jam'],
    ['Butter', 'Cheese', 'Bread'],
    ['Curd', 'Bread'],
    ['Cheese', 'Jam', 'Milk'],
    ['Banana', 'Apples', 'Bread', 'Butter', 'Milk'],
    ['Jam', 'Cheese', 'Butter', 'Apples'],
    ['Milk', 'Butter'],
    ['Bread', 'Butter', 'Coffee'],
    ['Jam', 'Banana', 'Cheese', 'Bread'],
    ['Cheese', 'Butter', 'Jam'],
    ['Bread', 'Eggs', 'Butter', 'Coffee', 'Banana'],
    ['Jam', 'Apples', 'Butter', 'Cheese'],
    ['Milk', 'Butter', 'Coffee'],
    ['Curd', 'Jam', 'Bread'],
    ['Coffee', 'Cheese', 'Butter'],
    ['Banana', 'Curd', 'Coffee', 'Bread', 'Eggs'],
    ['Butter', 'Apples', 'Jam'],
    ['Coffee', 'Curd', 'Apples', 'Eggs', 'Bread'],
    ['Apples', 'Banana', 'Bread'],
    ['Bread', 'Eggs'],
    ['Eggs', 'Curd', 'Bread', 'Butter', 'Apples'],
    ['Banana', 'Apples', 'Jam', 'Coffee'],
    ['Bread', 'Apples'],
    ['Cheese', 'Bread', 'Jam'],
    ['Eggs', 'Banana', 'Milk', 'Cheese'],
    ['Jam', 'Apples', 'Eggs', 'Coffee', 'Milk'],
    ['Jam', 'Apples', 'Butter', 'Bread', 'Eggs'],
    ['Apples', 'Coffee', 'Milk'],
    ['Cheese', 'Banana', 'Milk', 'Apples'],
    ['Jam', 'Butter', 'Milk'],
    ['Coffee', 'Bread', 'Apples'],
    ['Banana', 'Bread', 'Eggs', 'Apples', 'Cheese'],
    ['Apples', 'Eggs', 'Jam', 'Banana'],
    ['Curd', 'Butter', 'Apples', 'Cheese'],
    ['Curd', 'Cheese', 'Banana'],
    ['Banana', 'Bread', 'Butter', 'Apples'],
    ['Cheese', 'Milk'],
    ['Apples', 'Butter', 'Coffee', 'Milk'],
    ['Milk', 'Butter'],
    ['Milk', 'Cheese'],
    ['Apples', 'Butter'],
    ['Banana', 'Butter', 'Eggs'],
    ['Coffee', 'Banana', 'Butter', 'Curd', 'Apples'],
    ['Butter', 'Bread', 'Apples', 'Cheese'],
    ['Cheese', 'Curd', 'Apples', 'Butter'],
    ['Milk', 'Bread', 'Coffee', 'Butter', 'Cheese'],
    ['Bread', 'Butter', 'Apples'],
    ['Apples', 'Banana', 'Eggs'],
    ['Eggs', 'Jam', 'Banana', 'Bread'],
    ['Banana', 'Apples'],
    ['Milk', 'Apples'],
    ['Bread', 'Butter'],
    ['Curd', 'Banana', 'Apples'],
    ['Curd', 'Milk', 'Eggs'],
    ['Milk', 'Curd', 'Jam', 'Apples'],
    ['Jam', 'Curd', 'Banana', 'Bread'],
    ['Jam', 'Butter', 'Milk'],
    ['Apples', 'Milk', 'Cheese', 'Coffee'],
    ['Coffee', 'Banana'],
    ['Apples', 'Eggs', 'Milk', 'Jam'],
    ['Eggs', 'Bread'],
    ['Bread', 'Butter', 'Curd', 'Milk'],
    ['Butter', 'Milk', 'Bread', 'Coffee'],
    ['Coffee', 'Apples', 'Cheese', 'Eggs', 'Bread'],
    ['Cheese', 'Butter', 'Jam', 'Apples', 'Bread'],
    ['Jam', 'Banana', 'Cheese', 'Curd', 'Milk'],
    ['Banana', 'Bread'],
    ['Apples', 'Butter'],
    ['Jam', 'Eggs', 'Cheese', 'Milk'],
    ['Cheese', 'Jam', 'Eggs'],
    ['Apples', 'Jam', 'Milk', 'Cheese'],
    ['Jam', 'Bread', 'Eggs', 'Banana'],
    ['Bread', 'Apples'],
    ['Jam', 'Coffee', 'Butter'],
    ['Cheese', 'Butter', 'Jam', 'Banana', 'Apples'],
    ['Milk', 'Bread', 'Curd'],
    ['Milk', 'Coffee', 'Cheese'],
    ['Jam', 'Eggs', 'Banana'],
    ['Curd', 'Apples', 'Milk', 'Banana'],
    ['Eggs', 'Apples'],
    ['Cheese', 'Apples'],
    ['Curd', 'Eggs', 'Milk'],
    ['Cheese', 'Milk', 'Coffee'],
    ['Butter', 'Bread', 'Cheese'],
    ['Curd', 'Eggs', 'Butter', 'Coffee'],
    ['Eggs', 'Curd', 'Milk'],
    ['Cheese', 'Curd', 'Butter'],
    ['Eggs', 'Bread', 'Curd'],
    ['Banana', 'Butter'],
    ['Banana', 'Cheese', 'Jam'],
    ['Butter', 'Milk', 'Coffee'],
    ['Cheese', 'Jam', 'Bread', 'Curd'],
    ['Cheese', 'Apples', 'Curd'],
    ['Apples', 'Cheese', 'Milk', 'Banana', 'Eggs'],
]

# Emoji + a friendly price (in Rupees) for each catalog item so the shop
# tab feels like a real quick-commerce app.
ITEM_CATALOG = {
    'Bread':   {'emoji': '🍞', 'price': 45},
    'Milk':    {'emoji': '🥛', 'price': 32},
    'Jam':     {'emoji': '🍓', 'price': 99},
    'Coffee':  {'emoji': '☕', 'price': 210},
    'Curd':    {'emoji': '🥣', 'price': 40},
    'Apples':  {'emoji': '🍎', 'price': 180},
    'Butter':  {'emoji': '🧈', 'price': 55},
    'Banana':  {'emoji': '🍌', 'price': 48},
    'Cheese':  {'emoji': '🧀', 'price': 120},
    'Eggs':    {'emoji': '🥚', 'price': 78},
}
